/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BuyerRouteImport } from './routes/buyer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as AdminEventsTestRouteImport } from './routes/admin/events-test'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as AreaNameRouteImport } from './routes/area.$name'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as BrokerSubscriptionRouteImport } from './routes/broker/subscription'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as VerifyBrokerIdRouteImport } from './routes/verify.$brokerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRoute = BuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsTestRoute = AdminEventsTestRouteImport.update({
  id: '/admin/events-test',
  path: '/admin/events-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaNameRoute = AreaNameRouteImport.update({
  id: '/area/$name',
  path: '/area/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerSubscriptionRoute = BrokerSubscriptionRouteImport.update({
  id: '/broker/subscription',
  path: '/broker/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyBrokerIdRoute = VerifyBrokerIdRouteImport.update({
  id: '/verify/$brokerId',
  path: '/verify/$brokerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buyer': typeof BuyerRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/pricing': typeof PricingRoute
  '/seller': typeof SellerRoute
  '/admin/events-test': typeof AdminEventsTestRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/api/tts': typeof ApiTtsRoute
  '/area/$name': typeof AreaNameRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/broker/subscription': typeof BrokerSubscriptionRoute
  '/property/$id': typeof PropertyIdRoute
  '/verify/$brokerId': typeof VerifyBrokerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buyer': typeof BuyerRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/pricing': typeof PricingRoute
  '/seller': typeof SellerRoute
  '/admin/events-test': typeof AdminEventsTestRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/api/tts': typeof ApiTtsRoute
  '/area/$name': typeof AreaNameRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/broker/subscription': typeof BrokerSubscriptionRoute
  '/property/$id': typeof PropertyIdRoute
  '/verify/$brokerId': typeof VerifyBrokerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buyer': typeof BuyerRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/pricing': typeof PricingRoute
  '/seller': typeof SellerRoute
  '/admin/events-test': typeof AdminEventsTestRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/api/tts': typeof ApiTtsRoute
  '/area/$name': typeof AreaNameRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/broker/subscription': typeof BrokerSubscriptionRoute
  '/property/$id': typeof PropertyIdRoute
  '/verify/$brokerId': typeof VerifyBrokerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/buyer'
    | '/contact'
    | '/favorites'
    | '/pricing'
    | '/seller'
    | '/admin/events-test'
    | '/admin/subscriptions'
    | '/api/tts'
    | '/area/$name'
    | '/auth/login'
    | '/auth/register'
    | '/broker/subscription'
    | '/property/$id'
    | '/verify/$brokerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/buyer'
    | '/contact'
    | '/favorites'
    | '/pricing'
    | '/seller'
    | '/admin/events-test'
    | '/admin/subscriptions'
    | '/api/tts'
    | '/area/$name'
    | '/auth/login'
    | '/auth/register'
    | '/broker/subscription'
    | '/property/$id'
    | '/verify/$brokerId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/buyer'
    | '/contact'
    | '/favorites'
    | '/pricing'
    | '/seller'
    | '/admin/events-test'
    | '/admin/subscriptions'
    | '/api/tts'
    | '/area/$name'
    | '/auth/login'
    | '/auth/register'
    | '/broker/subscription'
    | '/property/$id'
    | '/verify/$brokerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuyerRoute: typeof BuyerRoute
  ContactRoute: typeof ContactRoute
  FavoritesRoute: typeof FavoritesRoute
  PricingRoute: typeof PricingRoute
  SellerRoute: typeof SellerRoute
  AdminEventsTestRoute: typeof AdminEventsTestRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  ApiTtsRoute: typeof ApiTtsRoute
  AreaNameRoute: typeof AreaNameRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BrokerSubscriptionRoute: typeof BrokerSubscriptionRoute
  PropertyIdRoute: typeof PropertyIdRoute
  VerifyBrokerIdRoute: typeof VerifyBrokerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer': {
      id: '/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events-test': {
      id: '/admin/events-test'
      path: '/admin/events-test'
      fullPath: '/admin/events-test'
      preLoaderRoute: typeof AdminEventsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area/$name': {
      id: '/area/$name'
      path: '/area/$name'
      fullPath: '/area/$name'
      preLoaderRoute: typeof AreaNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker/subscription': {
      id: '/broker/subscription'
      path: '/broker/subscription'
      fullPath: '/broker/subscription'
      preLoaderRoute: typeof BrokerSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$brokerId': {
      id: '/verify/$brokerId'
      path: '/verify/$brokerId'
      fullPath: '/verify/$brokerId'
      preLoaderRoute: typeof VerifyBrokerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuyerRoute: BuyerRoute,
  ContactRoute: ContactRoute,
  FavoritesRoute: FavoritesRoute,
  PricingRoute: PricingRoute,
  SellerRoute: SellerRoute,
  AdminEventsTestRoute: AdminEventsTestRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  ApiTtsRoute: ApiTtsRoute,
  AreaNameRoute: AreaNameRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BrokerSubscriptionRoute: BrokerSubscriptionRoute,
  PropertyIdRoute: PropertyIdRoute,
  VerifyBrokerIdRoute: VerifyBrokerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
